timestamp_error
upb-uc4/hlf-chaincode pull request #208
Opened 2021-03-02 09:56 UTC by NikoBergemann

- Add time error in cUtil
- add timestampCheck to every transaction
- restructure transactions for consistency and maintainability
- update tests to mock current time during execution

Co-authored-by: Matthias Geuchen <mgeuchen@mail.uni-paderborn.de>
Co-authored-by: Steffen Luis <sluis1@mail.uni-paderborn.de>
Co-authored-by: Anemone Kampkötter <anemone@kampkoetter.de>

2021-03-03 07:53 UTC, matthias-geuchen approved these changes

2021-03-05 09:25 UTC, sluis1 commented on CHANGELOG.md
> +- check Transactions for timestamp validity
```suggestion
- check transactions for timestamp validity

```

2021-03-05 09:31 UTC, anemonekk approved these changes

2021-03-05 09:33 UTC, sluis1 requested changes
just change the upper case in transactions

2021-03-05 14:03 UTC, sluis1 approved these changes

2021-03-05 14:03 UTC, merged