Feature/fix approving identity
upb-uc4/hlf-chaincode pull request #90
Opened 2020-12-15 16:39 UTC by matthias-geuchen

### Reason for this PR
- when adding new matriculation data, the contract should check if the existing approvals suffice

### Changes in this PR
- addmatriculationData now checks approvals
- add groups to approvals
- update tests
- add submission result
- add AccessManager for required approvals

2020-12-15 17:16 UTC, NikoBergemann commented on UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/ApprovalList.java
> +        sb.append("    users: ").append(toIndentedString(users)).append("\n");
```suggestion
        sb.append("class MatriculationData {\n");
        sb.append("    users: ").append(toIndentedString(users)).append("\n");
```

2020-12-15 17:17 UTC, NikoBergemann commented on UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/MatriculationData.java
> +        sb.append("    enrollmentId: ").append(toIndentedString(enrollmentId)).append("\n");
```suggestion
        sb.append("class MatriculationData {\n");
        sb.append("    enrollmentId: ").append(toIndentedString(enrollmentId)).append("\n");
```

2020-12-15 17:17 UTC, NikoBergemann commented on UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/SubjectMatriculation.java
> +        sb.append("    fieldOfStudy: ").append(toIndentedString(fieldOfStudy)).append("\n");
```suggestion
        sb.append("class SubjectImmatriculationInterval {\n");
        sb.append("    fieldOfStudy: ").append(toIndentedString(fieldOfStudy)).append("\n");
```

2020-12-15 17:18 UTC, NikoBergemann commented on UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/DetailedError.java
> +        sb.append("    type: ").append(toIndentedString(type)).append("\n");
```suggestion
        sb.append("class DetailedError {\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
```

2020-12-15 17:18 UTC, NikoBergemann commented on UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/GenericError.java
> +        sb.append("    type: ").append(toIndentedString(type)).append("\n");
```suggestion
        sb.append("class DetailedError {\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
```

2020-12-15 17:18 UTC, NikoBergemann commented on UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/model/errors/InvalidParameter.java
> +        sb.append("    name: ").append(toIndentedString(name)).append("\n");
```suggestion
        sb.append("class InvalidParameter {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
```

2020-12-15 17:23 UTC, NikoBergemann commented on UC4-chaincode/src/main/java/de/upb/cs/uc4/chaincode/util/helper/GsonWrapper.java
> +    private static final Gson gson = new GsonBuilder().disableHtmlEscaping()
```suggestion
    private static final Gson gson = new GsonBuilder()
```

2020-12-15 17:24 UTC, NikoBergemann requested changes
changes as commented in single comments

2020-12-18 12:49 UTC, mco33415 approved these changes

2021-01-04 14:25 UTC, NikoBergemann approved these changes

2021-01-04 14:25 UTC, merged